import test from 'node:test';
import assert from 'node:assert/strict';
import {DateTime} from 'luxon';
import {recommend,resolveRange,calendarAt,culturalResult,compare,validateInput} from '../scripts/core.js';
import {selectPlan,amendInput,reviewPlan,recordSubmission,backplan} from '../scripts/plans.js';
import {render,exportIcs,directionSvg} from '../scripts/render.js';
import {validateReport} from '../scripts/validate-report.js';
function input(extra={}){return {mode:'project',now:'2026-09-14T00:00:00+08:00',timezone:'Asia/Shanghai',
 project:{title:'Synthetic paper',stage:'initial',manuscript_version:'v1'},readiness:{status:'ready'},deadline:{status:'none'},
 range:{mode:'custom',start_date:'2026-09-21',end_date_exclusive:'2026-09-24'},...extra};}
const r=recommend(input());
test('three different dates and correct report contract',()=>{assert.equal(r.recommendations.length,3);assert.equal(new Set(r.recommendations.map(c=>c.local_date)).size,3);assert.ok(validateReport(r));});
test('Sunday next week',()=>assert.equal(resolveRange(input({range:{mode:'next_week'}}),DateTime.fromISO('2026-09-13T10:00:00+08:00')).start.toISODate(),'2026-09-14'));
test('Monday next week is following Monday',()=>assert.equal(resolveRange(input({range:{mode:'next_week'}}),DateTime.fromISO('2026-09-14T10:00:00+08:00')).start.toISODate(),'2026-09-21'));
test('local date controls week across UTC boundary',()=>assert.equal(resolveRange(input({range:{mode:'next_week'}}),DateTime.fromISO('2026-09-13T20:00:00Z')).start.toISODate(),'2026-09-21'));
test('cross year',()=>assert.equal(resolveRange(input({range:{mode:'next_week'}}),DateTime.fromISO('2026-12-31T10:00:00+08:00')).start.toISODate(),'2027-01-04'));
test('leap range',()=>assert.equal(resolveRange(input({range:{mode:'custom',start_date:'2024-02-28',end_date_exclusive:'2024-03-01'}}),DateTime.utc()).end.diff(DateTime.fromISO('2024-02-28',{zone:'Asia/Shanghai'}),'days').days,2));
test('rolling seven local days',()=>{const n=DateTime.fromISO('2026-09-14T10:17:00+08:00');const x=resolveRange(input({range:{mode:'rolling_7_days'}}),n);assert.equal(x.start.minute,17);assert.equal(x.end.diff(x.start,'days').days,7);});
test('reversed range rejected',()=>assert.throws(()=>recommend(input({range:{mode:'custom',start_date:'2026-09-25',end_date_exclusive:'2026-09-21'}}))));
test('unknown zone rejected',()=>assert.throws(()=>recommend(input({timezone:'Not/AZone'}))));
test('private input fields rejected',()=>assert.throws(()=>recommend({...input(),birth_data:'private'})));
test('impossible click offset rejected',()=>assert.throws(()=>recommend(input({preferences:{operation_minutes:5,click_offset_minutes:10}}))));
test('empty explicit availability means none',()=>assert.equal(recommend(input({availability:[]})).status,'no_candidates'));
test('readiness blocked',()=>assert.equal(recommend(input({readiness:{status:'blocked'}})).status,'no_candidates'));
test('unknown readiness remains conditional',()=>assert.equal(recommend(input({readiness:{status:'unknown'}})).status,'conditional'));
test('conditions preserved',()=>assert.deepEqual(recommend(input({readiness:{status:'conditional',conditions:['approval']}})).recommendations[0].conditions,['approval']));
test('ready after excludes earlier windows',()=>assert.ok(recommend(input({readiness:{status:'conditional',ready_after:'2026-09-23T12:00:00+08:00'}})).recommendations.every(c=>DateTime.fromISO(c.start_utc)>=DateTime.fromISO('2026-09-23T12:00:00+08:00'))));
test('deadline intersects full interval, not only click',()=>{const x=recommend(input({deadline:{status:'user_supplied',at:'2026-09-21T09:25:00+08:00',source:'synthetic'}}));assert.equal(x.status,'no_candidates');});
test('soft buffer permits remaining time',()=>{const x=recommend(input({deadline:{status:'user_supplied',at:'2026-09-21T11:00:00+08:00',source:'synthetic'}}));assert.ok(x.recommendations.length);assert.equal(x.recommendations[0].buffer_met,false);});
test('hard buffer cannot relax',()=>assert.equal(recommend(input({deadline:{status:'user_supplied',at:'2026-09-21T11:00:00+08:00',source:'synthetic'},preferences:{buffer_mode:'hard'}})).status,'no_candidates'));
test('AoE conversion explicit offset',()=>assert.equal(DateTime.fromISO('2026-09-22T23:59:59-12:00',{setZone:true}).setZone('Asia/Shanghai').toISO(),'2026-09-23T19:59:59.000+08:00'));
test('unknown deadline flagged',()=>assert.ok(recommend(input({deadline:{status:'unknown'}})).missing_inputs.includes('deadline')));
test('fake verified deadline without source rejected',()=>assert.throws(()=>recommend(input({deadline:{status:'verified',at:'2026-09-22T10:00:00Z'}}))));
test('exclusions respected',()=>{const x=recommend(input({excluded_intervals:[{start:'2026-09-21T00:00:00+08:00',end:'2026-09-22T00:00:00+08:00'}]}));assert.ok(x.recommendations.every(c=>c.local_date!=='2026-09-21'));});
test('same input deterministic candidates',()=>assert.deepEqual(recommend(input()).recommendations,r.recommendations));
test('nonoverlap when filling one day',()=>{const x=recommend(input({range:{mode:'custom',start_date:'2026-09-21',end_date_exclusive:'2026-09-22'}}));for(let i=0;i<x.recommendations.length;i++)for(let j=i+1;j<x.recommendations.length;j++)assert.ok(x.recommendations[i].end_utc<=x.recommendations[j].start_utc||x.recommendations[j].end_utc<=x.recommendations[i].start_utc);});
test('foreign zone explicitly degrades tradition',()=>{const x=recommend(input({timezone:'America/New_York'}));assert.equal(x.status,'degraded');assert.equal(x.recommendations[0].direction,null);});
test('strict tradition cannot silently degrade',()=>assert.equal(recommend(input({timezone:'America/New_York',preferences:{strict_traditional:true}})).status,'no_candidates'));
test('DST nonexistent wall time not emitted',()=>{const x=recommend(input({timezone:'America/New_York',now:'2026-03-01T00:00:00Z',range:{mode:'custom',start_date:'2026-03-08',end_date_exclusive:'2026-03-09'},availability:[{start:'2026-03-08T01:30:00-05:00',end:'2026-03-08T04:00:00-04:00'}]}));assert.ok(x.recommendations.length);assert.ok(x.recommendations.every(c=>!c.local_start.includes('T02:')));});
test('DST repeat keeps offsets and elapsed duration',()=>{const x=recommend(input({timezone:'America/New_York',now:'2026-10-01T00:00:00Z',range:{mode:'custom',start_date:'2026-11-01',end_date_exclusive:'2026-11-02'},availability:[{start:'2026-11-01T01:00:00-04:00',end:'2026-11-01T02:00:00-05:00'}]}));assert.ok(x.recommendations.every(c=>DateTime.fromISO(c.end_utc).diff(DateTime.fromISO(c.start_utc),'minutes').minutes===30));});
const fixtureDays=['癸酉','甲戌','乙亥','丙子','丁丑','戊寅','己卯','庚辰'];
fixtureDays.forEach((expected,i)=>test('calendar anchor + independently counted day '+i,()=>assert.equal(calendarAt(DateTime.fromISO('1986-05-29T09:00:00+08:00',{setZone:true}).plus({days:i})).day_ganzhi,expected)));
test('README anchor direction',()=>assert.equal(calendarAt(DateTime.fromISO('1986-05-29T09:00:00+08:00',{setZone:true})).xi_direction,'东南'));
test('cultural mode needs no project or time',()=>assert.equal(recommend({mode:'cultural'}).status,'ok'));
test('unknown excerpt cannot fabricate quotation',()=>assert.throws(()=>culturalResult({cultural:{excerpt_id:'missing'}})));
test('line changes bottom to top',()=>{const c=culturalResult({cultural:{action:'cast',lines:[6,7,8,9,7,8]}});assert.deepEqual(c.original_bottom_to_top,[0,1,0,1,1,0]);assert.deepEqual(c.changed_bottom_to_top,[1,1,0,0,1,0]);assert.deepEqual(c.moving_lines,[1,4]);assert.deepEqual(culturalResult({cultural:{action:'continue_reading',reading:c}}),c);});
test('bad line input rejected',()=>assert.throws(()=>recommend({mode:'cultural',cultural:{action:'cast',lines:[1,2,3,4,5,6]}})));
test('rendering depth does not mutate calculation',()=>{const before=JSON.stringify(r);render(r,'zh','detailed');render(r,'en');assert.equal(JSON.stringify(r),before);});
test('ICS absolute time and stable UID',()=>{const a=exportIcs(r),c=r.recommendations[0];assert.equal(a,exportIcs(r));assert.ok(a.includes('DTSTART:'+DateTime.fromISO(c.start_utc).toUTC().toFormat("yyyyMMdd'T'HHmmss'Z'")));assert.ok(a.split('\r\n').every(l=>Buffer.byteLength(l)<=75));assert.ok(!a.includes('BEGIN:VALARM'));});
test('direction diagram is not live compass',()=>assert.ok(directionSvg(r.recommendations[0].direction).includes('Not a live compass')));
test('compare uses real factors',()=>{const [a,b]=r.recommendations;assert.equal(compare(r,a.candidate_id,b.candidate_id).factors[2].a,a.sort_factors.cultural);});
test('patch preserves unrelated input and records changed fields',()=>{const x=input();const p=amendInput(x,{preferences:{preferred_hours:[14]}});assert.deepEqual(p.input.project,x.project);assert.equal(p.changes[0].field,'preferences');assert.equal(x.preferences,undefined);});
test('patch cannot inject unknown top-level field',()=>assert.throws(()=>amendInput(input(),{birth_data:'secret'})));
const plan=selectPlan(r,r.recommendations[0].candidate_id);
test('select preserves candidate',()=>assert.deepEqual(plan.candidate,r.recommendations[0]));
test('review does not reselect another time',()=>{const x=reviewPlan(plan,input(),'2026-09-20T08:00:00+08:00');assert.equal(x.state,'selected');assert.equal(x.candidate.candidate_id,plan.candidate.candidate_id);});
test('expired plan invalidated',()=>assert.equal(reviewPlan(plan,null,'2026-09-29T08:00:00+08:00').state,'invalidated'));
test('unverified review is not invalidated',()=>assert.equal(reviewPlan(plan,null,'2026-09-20T08:00:00+08:00').state,'needs_review'));
test('changed version requires review',()=>assert.equal(reviewPlan(plan,input({project:{title:'Synthetic paper',stage:'initial',manuscript_version:'v2'}}),'2026-09-20T08:00:00+08:00').state,'needs_review'));
test('submission confirmation required',()=>assert.throws(()=>recordSubmission(plan,{confirmed:false})));
test('submission unknown actual time remains missing and repeat idempotent',()=>{const x=recordSubmission(plan,{confirmed:true});assert.equal(x.submission.actual_clicked_at,undefined);assert.deepEqual(recordSubmission(x,{confirmed:true}),x);});
test('completed plan review remains completed',()=>{const x=recordSubmission(plan,{confirmed:true});assert.equal(reviewPlan(x,null).state,'submitted');});
test('cyclic tasks fail',()=>assert.throws(()=>backplan([{id:'a',minutes:1,depends_on:['b']},{id:'b',minutes:1,depends_on:['a']}],'2026-09-22T12:00:00Z',[])));
test('unknown task estimates explicit',()=>assert.equal(backplan([{id:'a'}],'2026-09-22T12:00:00Z',[]).status,'needs_estimates'));
test('backplanning respects dependency and never marks done',()=>{const x=backplan([{id:'a',minutes:30},{id:'b',minutes:30,depends_on:['a']}],'2026-09-22T12:00:00Z',[{start:'2026-09-22T09:00:00Z',end:'2026-09-22T12:00:00Z'}],'2026-09-22T08:00:00Z');assert.deepEqual(x.schedule.map(t=>t.id),['a','b']);assert.ok(x.schedule.every(t=>t.status==='planned'));});
test('not enough preparation time',()=>assert.equal(backplan([{id:'a',minutes:240}],'2026-09-22T12:00:00Z',[{start:'2026-09-22T11:00:00Z',end:'2026-09-22T12:00:00Z'}],'2026-09-22T08:00:00Z').status,'insufficient_time'));
test('source tampering fails report validation',()=>{const x=structuredClone(r);x.recommendations[0].direction.source_id='fake';assert.throws(()=>validateReport(x));});
test('local UTC mismatch fails report validation',()=>{const x=structuredClone(r);x.recommendations[0].local_click=x.recommendations[0].local_end;assert.throws(()=>validateReport(x));});
test('string false is not submission confirmation',()=>assert.throws(()=>recordSubmission(plan,{confirmed:'false'})));
test('changed allowed date range invalidates locked plan',()=>assert.equal(reviewPlan(plan,input({range:{mode:'custom',start_date:'2026-09-25',end_date_exclusive:'2026-09-26'}}),'2026-09-20T08:00:00+08:00').state,'invalidated'));
test('changed click offset requires explicit new selection',()=>{const x=reviewPlan(plan,input({preferences:{click_offset_minutes:20}}),'2026-09-20T08:00:00+08:00');assert.equal(x.state,'needs_review');assert.equal(x.candidate.click_at_utc,plan.candidate.click_at_utc);assert.notEqual(x.proposed_candidate.click_at_utc,plan.candidate.click_at_utc);});
test('changed readiness is not displayed as old ready state',()=>{const x=reviewPlan(plan,input({readiness:{status:'conditional',conditions:['approval']}}),'2026-09-20T08:00:00+08:00');assert.equal(x.state,'needs_review');assert.equal(x.candidate.readiness_status,'conditional');assert.deepEqual(x.candidate.conditions,['approval']);});
test('reverting preference clears proposed candidate and stabilizes revision',()=>{const x=reviewPlan(plan,input({preferences:{click_offset_minutes:20}}),'2026-09-20T08:00:00+08:00');const y=reviewPlan(x,input(),'2026-09-20T08:00:00+08:00');assert.equal(y.state,'selected');assert.equal(y.proposed_candidate,undefined);assert.equal(reviewPlan(y,input(),'2026-09-20T08:00:00+08:00').revision,y.revision);});
test('relative range does not move a locked plan on a new week',()=>{const x=reviewPlan(plan,input({range:{mode:'next_week'}}),'2026-09-21T08:00:00+08:00');assert.equal(x.state,'selected');});
